### ISSUE TITLE
HTTPS proxying broken in node 0.12.0

### ISSUE THREAD

**Issue by bls** [runk/node-thin#12]
Testing proxying on some HTTPS sites (e.g. http://test.com/ - note: that actual url :) in node.JS v0.12 results in a redirect loop. 

Turns out that the proxy was requesting all sites using HTTP, even when it should be using HTTPS. For sites which respond to an HTTP request with a redirect to HTTPS, this causes a loop.

The problem seems to be detection of https by this line in thin.js:

    schema = Boolean(req.client.pair) ? 'https' : 'http'

replacing this with:

    schema = req.connection.encrypted ? 'https' : 'http',

works in both 0.10 and 0.12.

**Comment by runk** [comment]
Done in v0.2.1
