### ISSUE TITLE
Getting MITM browser warning when using this tool

### ISSUE THREAD

**Issue by meshfields** [runk/node-thin#17]
I have the following setup:

```
Client -(ssl)-> node_thin -(ssl)-> Domain
```

..and I am getting a browser warning.

This is my code:

https://gist.github.com/nottinhill/60f64788dd8bbf6707a8

Any ideas what could be the issue?

**Comment by mk-pmb** [comment]
Does the browser warning have a message? Maybe even a details section? That could help a lot. However, most probably it will be about your browser not trusting the certificate you used for the proxy.
