### ISSUE TITLE
Proxy follows redirects by default

### ISSUE THREAD

**Issue by bls** [runk/node-thin#9]
The default options for 'thin' cause it to automatically follow redirects sent by the origin server. This breaks sites such as gmail login, or sites which use the OAuth 2.0 implicit grant type.

In the latter case, the server will respond with a 302 redirect which looks like:

    location: https://some-site.com/#access_token=<some-access-token-value>&token_type=bearer&state=whatever&scope=foo

The client needs to see the redirect (and process the fragment) to complete the authentication process. If the proxy follows redirects, it will swallow the fragment.

**Comment by runk** [comment]
Version `0.1.5` is out.

If you want to disable redirects, then do:

```
proxy = new Thin({followRedirect: false})
```

by default this property be enabled

**Comment by runk** [comment]
Thanks for feedback!

**Comment by bls** [comment]
Wow, that was quick, thanks :)

**Comment by runk** [comment]
My pleasure :)
